check if application is running before applying layout
evantravers/AutoLayout.spoon pull request #6
Opened 2023-09-01 22:34 UTC by wongjustin99

I noticed that AutoLayout was taking a very long time for me. It ended up being that Hammerspoon's `hs.application.find()` seems to be taking a while to time out if an application (e.g., zoom, brave) was not running. It would regularly take 6+ seconds on each Application's layout if it wasn't running. 

Not sure if this is the cleanest way to handle it -- but let me know your thoughts on this approach.

2023-09-02 02:39 UTC, evantravers commented
This is really cool! Let me dev test it a bit after the weekend.

2023-09-05 00:28 UTC, wongjustin99 commented
Sure thing!

The issue mainly occurred with stuff that had Title-matching that wasn't running. I run a program to quit stuff like Zoom if I don't use it for 10 minutes or so, so I would frequently run into AutoLayout hanging when looking for that main window title.

2023-09-05 18:55 UTC, wongjustin99 commented
I did a bit more research and found that it looks like `hs.application.find()` was timing out while checking for windows in each running application in `hs.window._timed_allWindows()`. 

I think this change might be unnecessary if the bug is fixed in hammerspoon (or I fix my unresponsive applications themselves). 

[Associated Issue](https://github.com/Hammerspoon/hammerspoon/issues/3450)

2023-09-11 14:30 UTC, evantravers commented
Sorry that I'm taking so long to respond… truth is I haven't been using AutoLayout for a bit, so it's been hard to dev test.

I was playing around with `hs.fnutils.filter` as a solution… how does this look to you? I don't know that it's any clearer or faster as code.

```lua
-- autoLayout() :: self
function m:autoLayout()
  -- Generate a table of running applications.
  local runningApps = {}
  for _, app in ipairs(hs.application.runningApplications()) do
    runningApps[app:name()] = true
  end

  -- Filter layouts to exclude "Unknown" apps and include only those apps that are currently running
  local filteredLayouts = hs.fnutils.ifilter(m.layouts(), function(layoutItem)
    local appName = layoutItem[1] and layoutItem[1]:name() or "Unknown"

    if appName ~= "Unknown" and runningApps[appName] then
      return true
    end

    return false
  end)

  -- Apply the filtered layouts
  hs.layout.apply(filteredLayouts, string.match)
  return self
end
```

I kinda want to untangle the "Unknown" as a comparison, feels like we could just return `false` if there isn't a `:name()` immediately.

2023-09-11 14:46 UTC, evantravers commented
@megalithic just suggested:

```lua
-- autoLayout() :: self
function m:autoLayout()
  -- Generate a table of running applications.
  local runningApps = {}
  for _, app in ipairs(hs.application.runningApplications()) do
    runningApps[app:name()] = true
  end

  -- Filter layouts to exclude "Unknown" apps and include only those apps that are currently running
  local filteredLayouts = hs.fnutils.ifilter(m.layouts(), function(layoutItem)
    return layoutItem[1] and layoutItem[1]:name() and runningApps[layoutItem[1]:name()]
  end)

  -- Apply the filtered layouts
  hs.layout.apply(filteredLayouts, string.match)
  return self
end
```

That feels pretty good… what do you think @wongjustin99?

2023-09-11 14:49 UTC, evantravers requested changes
Would you mind dev testing something like this? It's a little code golf-y, but it feels good.

2023-09-11 14:49 UTC, evantravers commented on init.lua
> +  -- Filter layouts to exclude "Unknown" apps and include only those apps that are currently running
Here's the suggestion in context:

```lua
  -- Filter layouts to exclude "Unknown" apps and include only those apps that are currently running
  local filteredLayouts = hs.fnutils.ifilter(m.layouts(), function(layoutItem)
    return layoutItem[1] and layoutItem[1]:name() and runningApps[layoutItem[1]:name()]
  end)
```

2023-09-13 19:44 UTC, merged

2023-09-14 06:49 UTC, fb-justin commented
Sorry it took so long for me to get back to you on this!

I just ran it locally (a lot of applications end up with "Undefined") and manually triggered autolayout and it looks great!

The suggestion from @metalithic seems much more idiomatic. I'm super new to lua hence the roundabout ways of handling that.

2023-09-14 06:50 UTC, wongjustin99 commented
Sorry it took so long for me to get back to you on this!

I just ran it locally (a lot of applications end up with "Undefined") and manually triggered autolayout and it looks great!

The suggestion from @metalithic seems much more idiomatic. I'm super new to lua hence the roundabout ways of handling that.

2023-09-14 19:27 UTC, evantravers commented
I merged it and updated it… thank you for helping me @wongjustin99!